import os
"""Batch-decompile holdouts with Ghidra, one draft file per function.

The point of the symbolized ELF is reconstruction at scale: 362 of the 491
declared holdouts are pure INCCODE stubs with no C body at all
(notes/holdouts-pure.md). This drives the whole list through Ghidra in one
analysis pass and writes the pseudo-C to disk, so drafts can be read and
compared against the m2c drafts without going through the MCP one at a time.

Ghidra analysis of the 8 MB ROM takes a few minutes; the project is cached
under `build/ghidra-proj`, so later runs reuse it and start immediately.

Usage:
  python3 tools/ghidra/batch_decompile.py                 # every pure stub
  python3 tools/ghidra/batch_decompile.py FlushOAM IsInHazard
  python3 tools/ghidra/batch_decompile.py --names-from FILE

Output: build/ghidra-drafts/<name>.c  (plus _index.md summarising the run)
"""
import io, os, re, sys

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
ELF = os.environ.get('RMZ3_SYM_ELF', os.path.join(REPO, 'build', 'rmz3_sym.elf'))
PROJ = os.path.join(REPO, 'build', 'ghidra-proj')
OUT = os.path.join(REPO, 'build', 'ghidra-drafts')
SYMS = os.path.join(REPO, 'tools', 'ghidra', 'rom_symbols.txt')
STUBS = os.path.join(REPO, 'notes', 'holdouts-pure.md')

# GHIDRA_INSTALL_DIR / JAVA_HOME come from the environment (.mcp.json sets both
# for the MCP server); no install path is baked into the repo.
for _v in ('GHIDRA_INSTALL_DIR', 'JAVA_HOME'):
    if not os.environ.get(_v):
        sys.exit('%s is not set -- export it, or copy the value from .mcp.json' % _v)

# `| NAKED static void drawZeroHPWeaponIcon(void* p)` -> drawZeroHPWeaponIcon
SIG = re.compile(r'`(?:NON_MATCH|NAKED)\b[^`]*?([A-Za-z_][A-Za-z_0-9]*)\s*\(')


def stub_names():
    if not os.path.exists(STUBS):
        sys.exit('run tools/classify_holdouts.py first (%s missing)' % STUBS)
    out = []
    for ln in io.open(STUBS, encoding='utf-8', errors='replace'):
        m = SIG.search(ln)
        if m:
            out.append(m.group(1))
    return sorted(set(out))


def sym_map():
    d = {}
    for ln in io.open(SYMS):
        p = ln.split()
        if len(p) >= 2:
            d[p[0]] = int(p[1], 16)
    return d


def main():
    argv = sys.argv[1:]
    if argv and argv[0] == '--names-from':
        names = [l.strip() for l in io.open(argv[1]) if l.strip()]
    elif argv:
        names = argv
    else:
        names = stub_names()

    syms = sym_map()
    known = [(n, syms[n]) for n in names if n in syms]
    missing = [n for n in names if n not in syms]
    print('%d requested, %d with a known address, %d unmapped'
          % (len(names), len(known), len(missing)))
    if not known:
        sys.exit('nothing to do')

    os.makedirs(OUT, exist_ok=True)
    os.makedirs(PROJ, exist_ok=True)

    import pyghidra
    pyghidra.start()

    ok, failed = [], []
    with pyghidra.open_program(ELF, project_location=PROJ,
                               project_name='rmz3', analyze=True) as flat:
        prog = flat.getCurrentProgram()
        space = prog.getAddressFactory().getDefaultAddressSpace()
        fm = prog.getFunctionManager()

        from ghidra.app.decompiler import DecompInterface
        di = DecompInterface()
        di.openProgram(prog)

        for i, (name, addr) in enumerate(known, 1):
            a = space.getAddress(addr)
            fn = fm.getFunctionAt(a) or fm.getFunctionContaining(a)
            if fn is None:
                failed.append((name, 'no function at %08X' % addr)); continue
            res = di.decompileFunction(fn, 120, None)
            if not res.decompileCompleted():
                failed.append((name, res.getErrorMessage() or 'decompile failed'))
                continue
            code = res.getDecompiledFunction().getC()
            with io.open(os.path.join(OUT, name + '.c'), 'w',
                         encoding='utf-8', newline='\n') as w:
                w.write(u'/* Ghidra draft: %s @ %08X\n'
                        u'   Pseudo-C, NOT a match. Cross-check against the m2c\n'
                        u'   draft before trusting the structure. */\n\n'
                        % (name, addr))
                w.write(code)
            ok.append(name)
            if i % 25 == 0:
                print('  %d/%d' % (i, len(known)))

    with io.open(os.path.join(OUT, '_index.md'), 'w',
                 encoding='utf-8', newline='\n') as w:
        w.write(u'# Ghidra drafts (%d)\n\n' % len(ok))
        w.write(u'Generated by `tools/ghidra/batch_decompile.py`. Pseudo-C, not\n'
                u'matches. Cross-check against m2c before trusting a structure.\n\n')
        for n in ok:
            w.write(u'- [%s](%s.c)\n' % (n, n))
        if failed:
            w.write(u'\n## Failed (%d)\n\n' % len(failed))
            for n, why in failed:
                w.write(u'- %s: %s\n' % (n, why))
        if missing:
            w.write(u'\n## No address in rom_symbols.txt (%d)\n\n' % len(missing))
            for n in missing:
                w.write(u'- %s\n' % n)

    print('decompiled %d, failed %d, unmapped %d -> %s'
          % (len(ok), len(failed), len(missing), OUT))


main()
